hw_project/hw_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("quotes.urls")),
    path("users/", include("users.urls"))
]

hw_project/quotes/urls.py
from django.urls import path

from . import views

app_name = "quotes"
urlpatterns = [
    path("", views.main, name="root"),
    path("<int:page>", views.main, name="root_paginate"),
    path("add_quote/", views.add_quote, name="add_quote"),
    path("add_author/", views.add_author, name="add_author"),
    path('add_tag/', views.add_tag, name='add_tag'),
    path('author/<int:pk>/', views.author_detail, name='author_detail'),
    path('tag/<slug:tag_name>/', views.tag_quotes, name='tag_quotes'),

]

hw_project/users/urls.py
from django.contrib.auth.views import PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView

from .forms import LoginForm
from .views import RegisterView, ResetPasswordView

app_name = "users"

urlpatterns = [
    path('signup/', RegisterView.as_view(), name='register'),
    path('signin/', LoginView.as_view(
        template_name="users/signin.html",
        authentication_form=LoginForm,
        redirect_authenticated_user=True
    ), name='login'),
    path('logout/', LogoutView.as_view(
        template_name="users/logout.html",
    ), name='logout'),
    path('reset-password/', ResetPasswordView.as_view(), name='password_reset'),
    path('reset-password/done/', PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'),
         name='password_reset_done'),
    path('reset-password/confirm/<uidb64>/<token>/',
         PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html',
                                          success_url='/users/reset-password/complete/'),
         name='password_reset_confirm'),
    path('reset-password/complete/',
         PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'),
         name='password_reset_complete'),
]

hw_project/quotes/models.py
from django.db import models

# Create your models here.


class Author(models.Model):
    fullname = models.CharField(max_length=50)
    date_born = models.CharField(max_length=50)
    born_location = models.CharField(max_length=150)
    bio = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.fullname


class Tag(models.Model):
    name = models.CharField(max_length=50, null=False, unique=True)

    def __str__(self):
        return self.name


class Quote(models.Model):
    quote = models.TextField()
    tags = models.ManyToManyField(Tag)
    author = models.ForeignKey(Author, on_delete=models.CASCADE, default=None, null=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.quote

hw_project/quotes/forms.py
from django.forms import ModelForm, CharField, TextInput, ModelMultipleChoiceField, SelectMultiple, ModelChoiceField, Select

from .models import Quote, Author, Tag


class QuoteForm(ModelForm):
    quote = CharField(min_length=5, required=True, widget=TextInput())
    tags = ModelMultipleChoiceField(queryset=Tag.objects.all().order_by("name"), required=True, widget=SelectMultiple())
    author = ModelChoiceField(queryset=Author.objects.all().order_by("fullname"), widget=Select())

    class Meta:
        model = Quote
        fields = ['quote', 'tags', 'author']


class AuthorForm(ModelForm):
    fullname = CharField(max_length=50, widget=TextInput())
    date_born = CharField(max_length=50, widget=TextInput())
    born_location = CharField(max_length=150, widget=TextInput())
    bio = CharField(widget=TextInput())

    class Meta:
        model = Author
        fields = ["fullname", "date_born", "born_location", "bio"]


class TagForm(ModelForm):
    name = CharField(max_length=50, widget=TextInput())


    class Meta:
        model = Tag
        fields = ["name"]

hw_project/quotes/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.core.paginator import Paginator
from django.db.models import Count
from .forms import QuoteForm, AuthorForm, TagForm

from .models import Quote, Tag, Author
# Create your views here.
from .utils import get_mongodb


def main(request, page=1):
    quotes = Quote.objects.all()
    paginator = Paginator(quotes, 10)
    page_obj = paginator.get_page(page)
    tags = Tag.objects.annotate(num_quotes=Count('quote')).order_by('-num_quotes')[:10]
    context = {'quotes': page_obj, 'tags': tags}
    return render(request, 'quotes/index.html', context)



def add_quote(request):
    if request.method == "POST":
        form = QuoteForm(request.POST)
        if form.is_valid():
            new_quote = form.save()
            return redirect(to="quotes:root")
        else:
            return render(request, "quotes/add_quote.html", context={'form': QuoteForm(), "message": "Form is not valid"})
    return render(request, "quotes/add_quote.html", context={'form': QuoteForm()})


def add_author(request):
    if request.method == "POST":
        form = AuthorForm(request.POST)
        if form.is_valid():
            new_author = form.save()
            return redirect(to="quotes:root")
        else:
            return render(request, "quotes/add_author.html", context={'form': AuthorForm(), "message": "Form is not valid"})
    return render(request, "quotes/add_author.html", context={'form': AuthorForm()})


def add_tag(request):
    if request.method == 'POST':
        form = TagForm(request.POST)
        if form.is_valid():
            name = form.cleaned_data['name']
            tag = Tag(name=name)
            tag.save()
            return redirect('quotes:root')
    else:
        form = TagForm()
    return render(request, 'quotes/add_tag.html', {'form': form})


def author_detail(request, pk):
    author = get_object_or_404(Author, pk=pk)
    quotes = Quote.objects.filter(author=author)
    return render(request, 'quotes/author_detail.html', {'author': author, 'quotes': quotes})


def tag_quotes(request, tag_name):
    tag = get_object_or_404(Tag, name=tag_name)
    quotes = Quote.objects.filter(tags__name=tag_name)

    context = {
        'tag': tag,
        'quotes': quotes,
    }
    return render(request, 'quotes/tag_quotes.html', context)

hw_project/quotes/templates/quotes/add_author.html
{% extends "quotes/base.html" %}

{% block content %}
<div class="container pt-3">
    <form method="POST" action="{% url 'quotes:add_author' %}" class="form mb-3">
        {% csrf_token %}
        <div class="form-group mb-3">
            <label class="form-label">Fullname</label>
            {{ form.fullname }}
            <span>{{ form.errors.fullname }}</span>
        </div>
        <div class="form-group mb-3">
            <label class="form-label">Born date</label>
            {{ form.date_born }}
            <span>{{ form.errors.date_born }}</span>
        </div>
        <div class="form-group mb-3">
            <label class="form-label">Born location</label>
            {{ form.born_location }}
          <span>{{ form.errors.born_location }}</span>
        </div>
        <div class="form-group mb-3">
            <label class="form-label">Bio</label>
            {{ form.bio }}
          <span>{{ form.errors.bio }}</span>
        </div>
        <div class="d-flex pt-3">
            <button class="btn btn-primary mx-2" type="submit">Submit</button>
            <button class="btn btn-secondary mx-2" type="reset">Reset</button>
        </div>
    </form>
</div>
{% endblock %}

hw_project/quotes/templates/quotes/add_quote.html
{% extends "quotes/base.html" %}

{% block content %}
<div class="container pt-3">
    <form method="POST" action="{% url 'quotes:add_quote' %}" class="form mb-3">
        {% csrf_token %}
        <div class="form-group mb-3">
            <label class="form-label">Author</label>
            {{ form.author }}
            <span>{{ form.errors.name }}</span>
        </div>
        <div class="form-group mb-3">
            <label class="form-label">Quote</label>
            {{ form.quote }}
            <span>{{ form.errors.description }}</span>
        </div>
        <div class="form-group mb-3">
            <label class="form-label">Tags</label>
            {{ form.tags }}
        </div>
        <div class="d-flex pt-3">
            <button class="btn btn-primary mx-2" type="submit">Submit</button>
            <button class="btn btn-secondary mx-2" type="reset">Reset</button>
        </div>
    </form>
</div>
{% endblock %}

hw_project/quotes/templates/quotes/add_tag.html
{% extends 'quotes/base.html' %}

{% block content %}
  <h2>Add a new tag</h2>
  <form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <button class="btn btn-primary mx-2" type="submit">Submit</button>
  </form>
{% endblock %}

hw_project/quotes/templates/quotes/author_detail.html
{% extends 'quotes/base.html' %}

{% block content %}
  <div class="author-details">
    <h1>{{ author.fullname }}</h1>
    <p>{{ author.bio }}</p>
    <h2>Quotes</h2>
    <ul class="author-quotes">
      {% for quote in quotes %}
        <li>{{ quote.quote }}</li>
      {% endfor %}
    </ul>
  </div>
{% endblock %}

hw_project/quotes/templates/quotes/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
    {% load static %}
    <link rel="stylesheet" href="{% static 'quotes/style.css' %}">
    <title>Homework</title>
</head>
<body>
    <div class="container">
        <div class="row header-box pt-3 mb-3">
            <div class="col-md-8">
                <h1>
                    <a href="/" style="text-decoration: none">Quotes to Scrape</a>
                </h1>
            </div>
                <div class="col-md-4">
                    <p>
                        {% if user.is_authenticated %}
                        <a href="{% url 'users:logout' %}" class="btn btn-primary">Logout </a>
                        <a href="{% url 'quotes:add_quote' %}" class="btn btn-primary">Add Quote </a>
                        <a href="{% url 'quotes:add_author' %}" class="btn btn-primary">Add Author </a>
                        <a href="{% url 'quotes:add_tag' %}" class="btn btn-primary">Add Tag </a>
                        {% else %}
                        <a href="{% url 'users:register' %}" class="btn btn-primary">SignUp</a>
                        <a href="{% url 'users:login' %}" class="btn btn-primary">Login</a>
                        {% endif %}

                    </p>
                </div>
        </div>

        {% block main %} {% endblock %}

        {% block content %} {% endblock %}


    </div>

</body>
</html>

hw_project/quotes/templates/quotes/index.html
{% extends 'quotes/base.html' %}
{% load extract %}

{% block content %}
    <div class="row">
        <div class="col-md-8">
            {% for quote in quotes %}
                <div class="quote" itemscope="" itemtype="http://schema.org/CreativeWork">
                    <span class="text" itemprop="text">
                        {{quote.quote}}
                    </span>
                    <span>by <small class="author" itemprop="author">{{quote.author_id|author}}</small>
                        <a href="{% url 'quotes:author_detail' pk=quote.author_id %}">(about)</a>
                    </span>
                    <div class="tags">
                        Tags:
                        {% for tag in quote.tags.all %}
                            <a class="tag" href="/tag/{{tag.name}}">{{tag.name}}</a>
                        {% endfor %}
                    </div>
                </div>
            {% endfor %}

            <nav>
                <ul class="pager">
                    <li class="previous">
                        <a class="{% if not quotes.has_previous %} disabled {% endif %}"
                           href="{% if quotes.has_previous %} {% url 'quotes:root_paginate' quotes.previous_page_number %} {% else %} # {% endif %}">
                            <span aria-hidden="true">←</span> Previous
                        </a>
                    </li>

                    <li class="next">
                        <a class="{% if not quotes.has_next %} disabled {% endif %}"
                           href="{% if quotes.has_next %} {% url 'quotes:root_paginate' quotes.next_page_number %} {% else %} # {% endif %}">
                            Next <span aria-hidden="true">→</span>
                        </a>
                    </li>

                    {% if quotes.has_next %}
                    <li class="last">
                        <a href="{% url 'quotes:root_paginate' quotes.paginator.num_pages %}">Last page</a>
                    </li>
                    {% endif %}
                </ul>
                </ul>
            </nav>
        </div>

        <div class="col-md-4">
            <div class="card mb-3">
                <div class="card-header">
                    Top Ten tags
                </div>
                <ul class="list-group list-group-flush">
                    {% for tag in tags %}
                    <li class="list-group-item d-flex justify-content-between align-items-center">
                        <a href="{% url 'quotes:tag_quotes' tag_name=tag.name %}" class="text-decoration-none">{{ tag.name }}</a>
                        <span class="badge bg-primary rounded-pill">{{ tag.num_quotes }}</span>
                    </li>
                    {% endfor %}
                </ul>
            </div>
        </div>
    </div>
{% endblock %}

hw_project/quotes/templates/quotes/tag_quotes.html
{% extends 'quotes/base.html' %}

{% block content %}
  <h1>Quotes with tag "{{ tag }}"</h1>
  <ul>
    {% for quote in quotes %}
      <li>{{ quote.quote }} - <em>{{ quote.author.fullname }}</em></li>
    {% endfor %}
  </ul>
{% endblock %}